apiVersion: v1
kind: Template
labels:
  template: approval-pam-secrets
metadata:
  name: approval-pam-secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: approval-pam-secrets
    labels:
      app: approval
  stringData:
    backoffice-token: "${BACKOFFICE_TOKEN}"
    approval-api-identity: "${APPROVAL_API_IDENTITY}"
    kie-admin-user: adminUser
    kie-admin-pwd: "${KIE_ADMIN_PWD}"
    kie-server-user: executionUser
    kie-server-pwd: "${KIE_SERVER_PWD}"
parameters:
- name: BACKOFFICE_TOKEN
  displayName: Backoffice API token
  required: true
  description: Backoffice API token
- name: APPROVAL_API_IDENTITY
  displayName: Approval API identity header
  required: true
  description: Identity header to access approval API
- name: KIE_ADMIN_PWD
  displayName: KIE Admin Password
  description: KIE administrator password
  from: "[a-zA-Z]{6}[0-9]{1}!"
  generate: expression
  required: false
- name: KIE_SERVER_PWD
  displayName: KIE Server Password
  description: KIE server password, used to connect to KIE servers. Generated value can be a suggestion to use for thew s2i various (Sets the org.kie.server.pwd system property)
  from: "[a-zA-Z]{6}[0-9]{1}!"
  generate: expression
  required: false
